/var/lib/slurm-llnl/slurmd/job49435/slurm_script: line 15: --batch_size: command not found
W0907 04:53:17.735000 23275992331328 torch/distributed/run.py:757] 
W0907 04:53:17.735000 23275992331328 torch/distributed/run.py:757] *****************************************
W0907 04:53:17.735000 23275992331328 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0907 04:53:17.735000 23275992331328 torch/distributed/run.py:757] *****************************************
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 3): env://, gpu 3
| distributed init (rank 1): env://, gpu 1| distributed init (rank 2): env://, gpu 2

[04:53:28.378091] job dir: /l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer
[04:53:28.378285] Namespace(batch_size=256,
train_classifier=True,
epochs=300,
accum_iter=1,
llama_model_path='./llama',
max_seq_len=512,
vqgan_ckt='/l/users/zhiqiang.shen/visual_tokenizer/checkpoints/V2LTokenizer/vqgan_checkpoint-last.pth',
weight_decay=0.05,
lr=0.00045,
blr=0.001,
min_lr=0.0,
warmup_epochs=5,
class_num=1000,
output_dir='/l/users/zhiqiang.shen/visual_tokenizer/checkpoints/gemma_vqgan_stage2_train_dataaug',
log_dir='/l/users/zhiqiang.shen/visual_tokenizer/checkpoints/gemma_vqgan_stage2_train_dataaug',
device='cuda',
seed=0,
resume='',
start_epoch=0,
num_workers=16,
pin_mem=True,
world_size=4,
local_rank=-1,
dist_on_itp=False,
dist_url='env://',
imagenet_path='/l/users/zhiqiang.shen/visual_tokenizer/data/ImageNet',
vqgan_path='vqgan_weight/vqgan_imagenet_f16_16384',
n_vision_words=32000,
output_type='next_token_prediction',
decode_rate=0,
n_class=1000,
vq_config_path='vqgan_configs/v2l.yaml',
image_size=128,
stage=2,
quantizer_type='org',
embed_dim=768,
use_cblinear=0,
use_crossatt_dec=0,
disc_start=10000,
rate_q=1.0,
rate_p=0.1,
rate_d=0.75,
rank=0,
gpu=0,
distributed=True,
dist_backend='nccl')
[04:53:28.378331] Start running basic DDP example on rank 0.
[04:53:28.378367] I am rank 0 using GPU 0 on host gpu-60
[rank1]: Traceback (most recent call last):
[rank1]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 489, in <module>
[rank1]:     main(args)
[rank1]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 301, in main
[rank1]:     dataset_train = ImageNetDataset(
[rank1]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 216, in __init__
[rank1]:     albumentations.RandomHorizontalFlip(),
[rank1]: AttributeError: module 'albumentations' has no attribute 'RandomHorizontalFlip'. Did you mean: 'HorizontalFlip'?
[rank3]: Traceback (most recent call last):
[rank3]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 489, in <module>
[rank3]:     main(args)
[rank3]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 301, in main
[rank3]:     dataset_train = ImageNetDataset(
[rank3]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 216, in __init__
[rank3]:     albumentations.RandomHorizontalFlip(),
[rank3]: AttributeError: module 'albumentations' has no attribute 'RandomHorizontalFlip'. Did you mean: 'HorizontalFlip'?
[rank0]: Traceback (most recent call last):
[rank0]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 489, in <module>
[rank0]:     main(args)
[rank0]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 301, in main
[rank0]:     dataset_train = ImageNetDataset(
[rank0]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 216, in __init__
[rank0]:     albumentations.RandomHorizontalFlip(),
[rank0]: AttributeError: module 'albumentations' has no attribute 'RandomHorizontalFlip'. Did you mean: 'HorizontalFlip'?
[rank2]: Traceback (most recent call last):
[rank2]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 489, in <module>
[rank2]:     main(args)
[rank2]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 301, in main
[rank2]:     dataset_train = ImageNetDataset(
[rank2]:   File "/l/users/zhiqiang.shen/visual_tokenizer/code/visual_tokenizer/V2L-Tokenizer/stage_2_train.py", line 216, in __init__
[rank2]:     albumentations.RandomHorizontalFlip(),
[rank2]: AttributeError: module 'albumentations' has no attribute 'RandomHorizontalFlip'. Did you mean: 'HorizontalFlip'?
E0907 04:53:42.771000 23275992331328 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 3466427) of binary: /home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/bin/python
Traceback (most recent call last):
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.1', 'console_scripts', 'torchrun')())
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
stage_2_train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-07_04:53:42
  host      : gpu-60
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3466428)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-07_04:53:42
  host      : gpu-60
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3466429)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-07_04:53:42
  host      : gpu-60
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3466430)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-07_04:53:42
  host      : gpu-60
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3466427)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
