W0828 21:38:16.982000 22391717536832 torch/distributed/run.py:757] 
W0828 21:38:16.982000 22391717536832 torch/distributed/run.py:757] *****************************************
W0828 21:38:16.982000 22391717536832 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0828 21:38:16.982000 22391717536832 torch/distributed/run.py:757] *****************************************
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:230: UserWarning: Overwriting vit_tiny_patch16_224 in registry with models.vit.vit_tiny_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_tiny_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:230: UserWarning: Overwriting vit_tiny_patch16_224 in registry with models.vit.vit_tiny_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_tiny_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:230: UserWarning: Overwriting vit_tiny_patch16_224 in registry with models.vit.vit_tiny_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_tiny_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:230: UserWarning: Overwriting vit_tiny_patch16_224 in registry with models.vit.vit_tiny_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_tiny_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:245: UserWarning: Overwriting vit_small_patch16_224 in registry with models.vit.vit_small_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_small_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:245: UserWarning: Overwriting vit_small_patch16_224 in registry with models.vit.vit_small_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_small_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:245: UserWarning: Overwriting vit_small_patch16_224 in registry with models.vit.vit_small_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_small_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:260: UserWarning: Overwriting vit_base_patch16_224 in registry with models.vit.vit_base_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:260: UserWarning: Overwriting vit_base_patch16_224 in registry with models.vit.vit_base_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:245: UserWarning: Overwriting vit_small_patch16_224 in registry with models.vit.vit_small_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_small_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:260: UserWarning: Overwriting vit_base_patch16_224 in registry with models.vit.vit_base_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:289: UserWarning: Overwriting vit_base_patch32_224 in registry with models.vit.vit_base_patch32_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch32_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:289: UserWarning: Overwriting vit_base_patch32_224 in registry with models.vit.vit_base_patch32_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch32_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:260: UserWarning: Overwriting vit_base_patch16_224 in registry with models.vit.vit_base_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch16_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:289: UserWarning: Overwriting vit_base_patch32_224 in registry with models.vit.vit_base_patch32_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch32_224(pretrained=False, **kwargs):
/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/models/vit.py:289: UserWarning: Overwriting vit_base_patch32_224 in registry with models.vit.vit_base_patch32_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def vit_base_patch32_224(pretrained=False, **kwargs):
I am rank 0 using GPU 0 on host gpu-02
| distributed init 4(rank 0)
I am rank 1 using GPU 1 on host gpu-02
| distributed init 4(rank 1)
I am rank 3 using GPU 3 on host gpu-02
| distributed init 4(rank 3)
I am rank 2 using GPU 2 on host gpu-02
| distributed init 4(rank 2)
Namespace(exp_name='test_llama', batch_size=2, epochs=300, wandb=False, model='vqgan_llama_small_patch16_224', input_size=224, drop=0.0, drop_path=0.1, model_ema=True, model_ema_decay=0.99996, model_ema_force_cpu=False, llama_path='/l/users/zhiqiang.shen/visual_tokenizer/checkpoints/llama/llama-2-7b', param_filter='llama.layers', use_patch_aug=False, opt='adamw', opt_eps=1e-08, opt_betas=None, clip_grad=None, momentum=0.9, weight_decay=0.05, sched='cosine', lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, warmup_lr=1e-06, min_lr=1e-05, decay_epochs=30, warmup_epochs=20, cooldown_epochs=10, patience_epochs=10, decay_rate=0.1, color_jitter=0.4, aa='rand-m9-mstd0.5-inc1', smoothing=0.1, train_interpolation='bicubic', repeated_aug=True, reprob=0.25, remode='pixel', recount=1, resplit=False, mixup=0.8, cutmix=1.0, cutmix_minmax=None, mixup_prob=1.0, mixup_switch_prob=0.5, mixup_mode='batch', teacher_model='regnety_160', teacher_path='', distillation_type='none', distillation_alpha=0.5, distillation_tau=1.0, finetune='', pretrained=False, data_path='/l/users/zhiqiang.shen/visual_tokenizer/data/ImageNet', data_set='IMNET', data_type='folder', inat_category='name', output_dir='/l/users/zhiqiang.shen/visual_tokenizer/checkpoints/vqgan_llama_classification', device='cuda', seed=0, resume='', start_epoch=0, eval=False, inc_path=None, ina_path=None, inr_path=None, insk_path=None, fgsm_test=False, pgd_test=False, dist_eval=False, num_workers=32, pin_mem=True, local_rank=0, world_size=4, dist_url='env://', test_every=1, distributed=True, dist_backend='nccl', rank=0)
Creating model: vqgan_llama_small_patch16_224
****Using LLaMA2 Token Embedding****
Word Number:32000
Text Feature Dim:4096
Visual Feature Dimension:  384
Embedding Dimension is: 384
Loading LLaMA checkpoints
Loaded in 4.56 seconds
Distributed
number of params: 3630184
Start training for 300 epochs
model:
  learning_rate: 4.5e-06
  params:
    ddconfig:
      attn_resolutions:
      - 16
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      double_z: false
      dropout: 0.0
      in_channels: 3
      num_res_blocks: 2
      out_ch: 3
      resolution: 256
      z_channels: 256
    embed_dim: 256
    monitor: val/rec_loss
  target: models_vqgan_llama.VQModel_LLaMA

num_res_blocks of Decoder is: 3
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
****Using Quantizer: org
****Using Random Token Embedding****
Word Number:32000
Feature Dim:768
loaded pretrained LPIPS loss from models/vgg.pth
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 643, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 582, in main
[rank0]:     train_stats = train_one_epoch(
[rank0]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/engine.py", line 84, in train_one_epoch
[rank0]:     for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
[rank0]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/utils.py", line 285, in log_every
[rank0]:     space_fmt = ':' + str(len(str(len(iterable)))) + 'd'
[rank0]: TypeError: object of type 'AdamW' has no len()
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 643, in <module>
[rank2]:     main(args)
[rank2]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 582, in main
[rank2]:     train_stats = train_one_epoch(
[rank2]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/engine.py", line 84, in train_one_epoch
[rank2]:     for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
[rank2]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/utils.py", line 285, in log_every
[rank2]:     space_fmt = ':' + str(len(str(len(iterable)))) + 'd'
[rank2]: TypeError: object of type 'AdamW' has no len()
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 643, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 582, in main
[rank1]:     train_stats = train_one_epoch(
[rank1]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/engine.py", line 84, in train_one_epoch
[rank1]:     for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
[rank1]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/utils.py", line 285, in log_every
[rank1]:     space_fmt = ':' + str(len(str(len(iterable)))) + 'd'
[rank1]: TypeError: object of type 'AdamW' has no len()
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 643, in <module>
[rank3]:     main(args)
[rank3]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/main.py", line 582, in main
[rank3]:     train_stats = train_one_epoch(
[rank3]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/engine.py", line 84, in train_one_epoch
[rank3]:     for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
[rank3]:   File "/home/zhiqiang.shen/projects/visual_tokenizer/V2L-Tokenizer/image_classification/utils.py", line 285, in log_every
[rank3]:     space_fmt = ':' + str(len(str(len(iterable)))) + 'd'
[rank3]: TypeError: object of type 'AdamW' has no len()
E0828 21:38:42.010000 22391717536832 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 1094358) of binary: /home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/bin/python
Traceback (most recent call last):
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.1', 'console_scripts', 'torchrun')())
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhiqiang.shen/anaconda3/envs/visual_tokenizer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-28_21:38:42
  host      : gpu-02
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1094359)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-28_21:38:42
  host      : gpu-02
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1094360)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-28_21:38:42
  host      : gpu-02
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1094361)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-28_21:38:42
  host      : gpu-02
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1094358)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
